### ISSUE TITLE
wsbackend-tasknode does not start

### ISSUE THREAD

**Issue by fyoorer** [lavalamp-/ws-docker-community#1]
I am trying out the dockerized deployment and all images are built successfully. But when I run initialize-data-stores.sh, it does not work because wsbackend-tasknode does not start.
I tried running it as standalone container to see whats going wrong. Apparently, kombu 4.0.2 and celery 3.1.25 are incompatible. See [this issue](https://github.com/celery/kombu/issues/632)

```
docker run --rm wsbackend-tasknode
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 7, in <module>
    from celery.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/celery/__init__.py", line 133, in <module>
    from celery import five  # noqa
  File "/usr/local/lib/python2.7/site-packages/celery/five.py", line 153, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
ImportError: cannot import name OrderedDict
```

**Comment by lavalamp-** [comment]
Thanks for pointing this out - I ran into a similar issue yesterday. Try pulling down the most recent versions of the backend and frontend code from within the docker git repo - this should be fixed in master (https://github.com/lavalamp-/ws-backend-community/blob/master/requirements.txt now has requirement of kombu==3.0.37).
